--PAIS
INSERT INTO COUNTRY(NAME,DDI) VALUES('BRASIL',55);
INSERT INTO COUNTRY(NAME,DDI) VALUES('EUA',1);
--ESTADOS
INSERT INTO STATE(NAME,id_country) VALUES('PARANÁ',(SELECT ID FROM COUNTRY WHERE NAME = 'BRASIL'));
INSERT INTO STATE(NAME,id_country) VALUES('SANTA CATARINA',(SELECT ID FROM COUNTRY WHERE NAME = 'BRASIL'));
INSERT INTO STATE(NAME,id_country) VALUES('RIO GRANDE DO SUL',(SELECT ID FROM COUNTRY WHERE NAME = 'BRASIL'));
INSERT INTO STATE(NAME,id_country) VALUES('SÃO PAULO',(SELECT ID FROM COUNTRY WHERE NAME = 'BRASIL'));
INSERT INTO STATE(NAME,id_country) VALUES('RIO DE JANEIRO',(SELECT ID FROM COUNTRY WHERE NAME = 'BRASIL'));
INSERT INTO STATE(NAME,id_country) VALUES('MINAS GERAIS',(SELECT ID FROM COUNTRY WHERE NAME = 'BRASIL'));
INSERT INTO STATE(NAME,id_country) VALUES('ESPÍRITO SANTO',(SELECT ID FROM COUNTRY WHERE NAME = 'BRASIL'));
INSERT INTO STATE(NAME,id_country) VALUES('MATO GROSSO DO SUL',(SELECT ID FROM COUNTRY WHERE NAME = 'BRASIL'));
INSERT INTO STATE(NAME,id_country) VALUES('MATO GROSSO',(SELECT ID FROM COUNTRY WHERE NAME = 'BRASIL'));
INSERT INTO STATE(NAME,id_country) VALUES('RONDONIA',(SELECT ID FROM COUNTRY WHERE NAME = 'BRASIL'));
INSERT INTO STATE(NAME,id_country) VALUES('GOIAS',(SELECT ID FROM COUNTRY WHERE NAME = 'BRASIL'));
INSERT INTO STATE(NAME,id_country) VALUES('TOCANTINS',(SELECT ID FROM COUNTRY WHERE NAME = 'BRASIL'));
INSERT INTO STATE(NAME,id_country) VALUES('PIAIU',(SELECT ID FROM COUNTRY WHERE NAME = 'BRASIL'));
INSERT INTO STATE(NAME,id_country) VALUES('RIO GRANDE DO NORTE',(SELECT ID FROM COUNTRY WHERE NAME = 'BRASIL'));
INSERT INTO STATE(NAME,id_country) VALUES('CEARA',(SELECT ID FROM COUNTRY WHERE NAME = 'BRASIL'));
INSERT INTO STATE(NAME,id_country) VALUES('PARAÍBA',(SELECT ID FROM COUNTRY WHERE NAME = 'BRASIL'));
INSERT INTO STATE(NAME,id_country) VALUES('PERNAMBUCO',(SELECT ID FROM COUNTRY WHERE NAME = 'BRASIL'));
INSERT INTO STATE(NAME,id_country) VALUES('ALAGOAS',(SELECT ID FROM COUNTRY WHERE NAME = 'BRASIL'));
INSERT INTO STATE(NAME,id_country) VALUES('SERGIPE',(SELECT ID FROM COUNTRY WHERE NAME = 'BRASIL'));
INSERT INTO STATE(NAME,id_country) VALUES('BAHIA',(SELECT ID FROM COUNTRY WHERE NAME = 'BRASIL'));
INSERT INTO STATE(NAME,id_country) VALUES('PARÁ',(SELECT ID FROM COUNTRY WHERE NAME = 'BRASIL'));
INSERT INTO STATE(NAME,id_country) VALUES('AMAZONAS',(SELECT ID FROM COUNTRY WHERE NAME = 'BRASIL'));
INSERT INTO STATE(NAME,id_country) VALUES('ACRE',(SELECT ID FROM COUNTRY WHERE NAME = 'BRASIL'));
INSERT INTO STATE(NAME,id_country) VALUES('RORAIMA',(SELECT ID FROM COUNTRY WHERE NAME = 'BRASIL'));
INSERT INTO STATE(NAME,id_country) VALUES('AMAPA',(SELECT ID FROM COUNTRY WHERE NAME = 'BRASIL'));
INSERT INTO STATE(NAME,id_country) VALUES('DISTRITO FEDERAL',(SELECT ID FROM COUNTRY WHERE NAME = 'BRASIL'));

--CIDADES
INSERT INTO CITY (NAME, latitude, longitude, ddd, id_state) VALUES('PATO BRANCO', -26.2295, -52.6716,46, (SELECT ID FROM STATE WHERE NAME = 'PARANÁ'));
INSERT INTO CITY (NAME, latitude, longitude, ddd, id_state) VALUES('FRANCISCO BELTRÃO', -26.2295, -52.6716,46, (SELECT ID FROM STATE WHERE NAME = 'PARANÁ'));
INSERT INTO CITY (NAME, latitude, longitude, ddd, id_state) VALUES('CURITIBA', -26.2295, -52.6716,41, (SELECT ID FROM STATE WHERE NAME = 'PARANÁ'));
INSERT INTO CITY (NAME, latitude, longitude, ddd, id_state) VALUES('CASCAVEL', -26.2295, -52.6716,45, (SELECT ID FROM STATE WHERE NAME = 'PARANÁ'));
INSERT INTO CITY (NAME, latitude, longitude, ddd, id_state) VALUES('FOZ DO IGUAÇU', -26.2295, -52.6716,45, (SELECT ID FROM STATE WHERE NAME = 'PARANÁ'));
INSERT INTO CITY (NAME, latitude, longitude, ddd, id_state) VALUES('MARINGA', -26.2295, -52.6716,44, (SELECT ID FROM STATE WHERE NAME = 'PARANÁ'));
INSERT INTO CITY (NAME, latitude, longitude, ddd, id_state) VALUES('LONDRINA', -26.2295, -52.6716,44, (SELECT ID FROM STATE WHERE NAME = 'PARANÁ'));
INSERT INTO CITY (NAME, latitude, longitude, ddd, id_state) VALUES('PONTA GROSSA', -26.2295, -52.6716,42, (SELECT ID FROM STATE WHERE NAME = 'PARANÁ'));
INSERT INTO CITY (NAME, latitude, longitude, ddd, id_state) VALUES('GUARAPUAVA', -26.2295, -52.6716,42, (SELECT ID FROM STATE WHERE NAME = 'PARANÁ'));
INSERT INTO CITY (NAME, latitude, longitude, ddd, id_state) VALUES('MATINHOS', -26.2295, -52.6716,41, (SELECT ID FROM STATE WHERE NAME = 'PARANÁ'));